import Head from "next/head";
import { useSelector } from "react-redux";
import Layout from "../components/Layout";

export default function ProfilePage() {
  const userState = useSelector((state) => {
    return state.userState;
  });
  const user = userState.user;
  return (
    <Layout>
      <Head>
        <title>SocioMedia | Profile - {user.firstName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          My name is {user.firstName} {user.lastName}
        </h1>
      </div>
    </Layout>
  );
}
