import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { setPosts } from "../../state/postSlice";
import fetchPosts from "../../utils/fetchPosts";
import AddForm from "../components/AddForm";
import Container from "../components/Container";
import Posts from "../components/Posts";
import Layout from "../Layout";

const Home = () => {
  const [postsList, setPostsList] = useState([]);
  const dispatch = useDispatch();
  const userState = useSelector((state) => {
    return state.userState;
  });
  const user = userState.user;
  const token = userState.token;

  useEffect(() => {
    const getPosts = async () => {
      if (user) {
        const data = await fetchPosts(token);

        if (data?.length >= 0) {
          dispatch(setPosts(data));
          setPostsList(data);
        }
      }
    };
    getPosts();
  }, []);

  return (
    <Layout>
      <Head>
        <title>SocioMedia | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <aside></aside>
        <main>
          <section className="py-4">
            <Container>
              <AddForm />
            </Container>
          </section>
          <section>
            <Container>
              <Posts posts={postsList} />
            </Container>
          </section>
        </main>
      </div>
    </Layout>
  );
};

export default Home;
