import Head from "next/head";
import React from "react";
import AddForm from "../components/AddForm";
import Container from "../components/Container";
import Layout from "../Layout";

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>SocioMedia | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <aside></aside>
        <main>
          <section className="py-4">
            <Container>
              <AddForm />
            </Container>
          </section>
          <section>
            <Container>Posts</Container>
          </section>
        </main>
      </div>
    </Layout>
  );
};

export default Home;
